//
// Created by bumman on 21/12/2021.
//

#ifndef C_SERVER_CONSTANT_H
#define C_SERVER_CONSTANT_H

#define BACKLOG 20
#define BUFF_SIZE 1024
//#define SEND_END "S1"
#define REGISTER_SUCCESS "70"
#define REGISTER_FAIL "71"
#define USER_EXIST "72"
#define ADD_PLACE_OK "81"
#define ADD_PLACE_ERR "80"
#define REMOVE_PLACE "9"
#define REMOVE_PLACE_OK "91"
#define REMOVE_PLACE_ERROR "90"
#define BACKUP_ERROR "100"
#define BACKUP_OK "101"
#define ADDFRIEND_SUCCESS "150"
#define ADDFRIEND_FAIL "151"
#define WAITING_ACCEPT "152"
#define SHOW_LIST_FAIL "161"
#define ACCEPT_FRIEND_SUCCESS "190"
#define ACCEPT_FRIEND_FAIL "191"
#define DELETE_REQUEST_FAIL "211"
#define DELETE_REQUEST_SUCCESS "210"
#define SEND_END "-1"

#endif //C_SERVER_CONSTANT_H
